---
inputs:
- name: e2e-source
caches:
- path: .gradle
platform: linux
image_resource:
  type: docker-image
  source: {repository: codebandits/rookery}
run:
  dir: e2e-source
  path: sh
  args:
  - -exc
  - |
    chown -R browsertests:browsertests .
    su browsertests -c 'xvfb-run ./gradlew --gradle-user-home=.gradle e2e:test'
