---
inputs:
- name: api-artifact
outputs:
- name: api-artifact-extract
platform: linux
image_resource:
  type: docker-image
  source: {repository: codebandits/rookery}
run:
  dir: api-artifact
  path: sh
  args:
  - -exc
  - |
    tar xzf api-*.tgz -C ../api-artifact-extract
