---
inputs:
- name: chat-web-artifact
outputs:
- name: chat-web-artifact-extract
platform: linux
image_resource:
  type: docker-image
  source: {repository: codebandits/rookery}
run:
  dir: chat-web-artifact
  path: sh
  args:
  - -exc
  - |
    tar xzf chat-*.tgz -C ../chat-web-artifact-extract
