---
inputs:
- name: api-version
- name: api-source
outputs:
- name: api-build
caches:
- path: .gradle
platform: linux
image_resource:
  type: docker-image
  source: {repository: codebandits/rookery}
run:
  dir: api-source
  path: sh
  args:
  - -exc
  - |
    VERSION=$(cat ../api-version/number)
    BUILD_DIR=../api-build/api-$VERSION
    ./gradlew --gradle-user-home=.gradle -Pversion=$VERSION api:test api:assemble
    mkdir -p $BUILD_DIR
    cp -r api/build/libs/api-$VERSION.jar api/deployment $BUILD_DIR
    echo "path: ../api-$VERSION.jar" | tee -a $BUILD_DIR/deployment/manifest-*.yml
    cd $BUILD_DIR
    tar czf ../api-$VERSION.tgz .
