---
inputs:
- name: chat-backend-version
- name: chat-backend-source
outputs:
- name: chat-backend-build
caches:
- path: .gradle
platform: linux
image_resource:
  type: docker-image
  source: {repository: codebandits/rookery}
run:
  dir: chat-backend-source
  path: sh
  args:
  - -exc
  - |
    VERSION=$(cat ../chat-backend-version/number)
    BUILD_DIR=../chat-backend-build/chat-backend-$VERSION
    ./gradlew --gradle-user-home=.gradle -Pversion=$VERSION chat/backend:test chat/backend:assemble
    mkdir -p $BUILD_DIR
    cp -r chat/backend/build/libs/chat-backend-$VERSION.jar chat/backend/deployment $BUILD_DIR
    echo "path: ../chat-backend-$VERSION.jar" | tee -a $BUILD_DIR/deployment/manifest-*.yml
    cd $BUILD_DIR
    tar czf ../chat-backend-$VERSION.tgz .
