jobs:

- name: publish ci image
  plan:
  - get: ci-image-source
    trigger: true
  - put: ci-image
    params:
      build: ci-image-source/pipeline/docker

- name: api
  plan:
  - aggregate:
    - get: ci-image
    - get: api-source
      trigger: true
    - get: api-version
      params: {bump: patch}
  - task: test and build
    image: ci-image
    config:
      inputs:
      - name: api-version
      - name: api-source
      outputs:
      - name: api-build
      caches:
      - path: .gradle
      platform: linux
      run:
        dir: api-source
        path: sh
        args:
        - -exc
        - |
          VERSION=$(cat ../api-version/number)
          BUILD_DIR=../api-build/api-$VERSION
          ./gradlew --gradle-user-home=.gradle -Pversion=$VERSION api:test api:assemble
          mkdir -p $BUILD_DIR
          cp -r api/build/libs/api-$VERSION.jar api/deployment $BUILD_DIR
          echo "path: ../api-$VERSION.jar" | tee -a $BUILD_DIR/deployment/manifest-*.yml
          cd $BUILD_DIR
          tar czf ../api-$VERSION.tgz .
  - put: api-artifact
    params:
      file: ./api-build/api-*.tgz
  - put: api-version
    params: {file: api-version/number}

- name: chat web
  plan:
  - aggregate:
    - get: ci-image
    - get: chat-web-source
      trigger: true
    - get: chat-web-version
      params: {bump: patch}
  - task: test and build
    image: ci-image
    config:
      inputs:
      - name: chat-web-version
      - name: chat-web-source
      outputs:
      - name: chat-web-build
      caches:
      - path: .gradle
      - path: chat/web/node_modules
      platform: linux
      run:
        dir: chat-web-source
        path: sh
        args:
        - -exc
        - |
          VERSION=$(cat ../chat-web-version/number)
          BUILD_DIR=../chat-web-build/chat-web-$VERSION
          ./gradlew --gradle-user-home=.gradle chat/web:yarn_install chat/web:yarn_test chat/web:yarn_run_build
          mkdir -p $BUILD_DIR
          cp -r chat/web/deployment $BUILD_DIR
          cp -r chat/web/build $BUILD_DIR/chat-web-$VERSION
          echo "path: ../chat-web-$VERSION" | tee -a $BUILD_DIR/deployment/manifest-*.yml
          cd $BUILD_DIR
          tar czf ../chat-web-$VERSION.tgz .
  - put: chat-web-artifact
    params:
      file: ./chat-web-build/chat-web-*.tgz
  - put: chat-web-version
    params: {file: chat-web-version/number}

- name: chat backend
  plan:
  - aggregate:
    - get: ci-image
    - get: chat-backend-source
      trigger: true
    - get: chat-backend-version
      params: {bump: patch}
  - task: test and build
    image: ci-image
    config:
      inputs:
      - name: chat-backend-version
      - name: chat-backend-source
      outputs:
      - name: chat-backend-build
      caches:
      - path: .gradle
      platform: linux
      run:
        dir: chat-backend-source
        path: sh
        args:
        - -exc
        - |
          VERSION=$(cat ../chat-backend-version/number)
          BUILD_DIR=../chat-backend-build/chat-backend-$VERSION
          ./gradlew --gradle-user-home=.gradle -Pversion=$VERSION chat/backend:test chat/backend:assemble
          mkdir -p $BUILD_DIR
          cp -r chat/backend/build/libs/chat-backend-$VERSION.jar chat/backend/deployment $BUILD_DIR
          echo "path: ../chat-backend-$VERSION.jar" | tee -a $BUILD_DIR/deployment/manifest-*.yml
          cd $BUILD_DIR
          tar czf ../chat-backend-$VERSION.tgz .
  - put: chat-backend-artifact
    params:
      file: ./chat-backend-build/chat-backend-*.tgz
  - put: chat-backend-version
    params: {file: chat-backend-version/number}

- name: e2e
  serial: true
  plan:
  - aggregate:
    - get: ci-image
    - get: e2e-source
      trigger: true
    - get: api-artifact
      trigger: true
      passed: [api]
    - get: chat-web-artifact
      trigger: true
      passed:
      - chat web
    - get: chat-backend-artifact
      trigger: true
      passed:
      - chat backend
  - aggregate:
    - task: extract api
      image: ci-image
      config:
        inputs:
        - name: api-artifact
        outputs:
        - name: api-artifact-extract
        platform: linux
        run:
          dir: api-artifact
          path: sh
          args:
          - -exc
          - |
            tar xzf api-*.tgz -C ../api-artifact-extract
    - task: extract chat web
      image: ci-image
      config:
        inputs:
        - name: chat-web-artifact
        outputs:
        - name: chat-web-artifact-extract
        platform: linux
        run:
          dir: chat-web-artifact
          path: sh
          args:
          - -exc
          - |
            tar xzf chat-*.tgz -C ../chat-web-artifact-extract
    - task: extract chat backend
      image: ci-image
      config:
        inputs:
        - name: chat-backend-artifact
        outputs:
        - name: chat-backend-artifact-extract
        platform: linux
        run:
          dir: chat-backend-artifact
          path: sh
          args:
          - -exc
          - |
            tar xzf chat-backend-*.tgz -C ../chat-backend-artifact-extract
  - aggregate:
    - put: cf-ci
      params:
        manifest: api-artifact-extract/deployment/manifest-ci.yml
        environment_variables:
          TWITTER_CONSUMER-KEY: ((twitter.ci.consumer-key))
          TWITTER_CONSUMER-SECRET: ((twitter.ci.consumer-secret))
          TWITTER_ACCESS-TOKEN: ((twitter.ci.access-token))
          TWITTER_ACCESS-TOKEN-SECRET: ((twitter.ci.access-token-secret))
    - put: cf-ci
      params:
        manifest: chat-web-artifact-extract/deployment/manifest-ci.yml
    - put: cf-ci
      params:
        manifest: chat-backend-artifact-extract/deployment/manifest-ci.yml

  - task: end to end tests
    image: ci-image
    params:
      API_URL: http://twauth-api-ci.cfapps.io/
      CHAT_URL: http://twauth-chat-ci.cfapps.io/
      TWITTER_USERNAME: ((e2e.twitter_username))
      TWITTER_PASSWORD: ((e2e.twitter_password))
    privileged: true
    config:
      inputs:
      - name: e2e-source
      caches:
      - path: .gradle
      platform: linux
      run:
        dir: e2e-source
        path: sh
        args:
        - -exc
        - |
          chown -R browsertests:browsertests .
          su browsertests -c 'xvfb-run ./gradlew --gradle-user-home=.gradle e2e:test'

- name: api production
  serial: true
  plan:
  - aggregate:
    - get: ci-image
    - get: api-artifact
      trigger: true
      passed:
      - e2e
  - task: extract api
    image: ci-image
    config:
      inputs:
      - name: api-artifact
      outputs:
      - name: api-artifact-extract
      platform: linux
      run:
        dir: api-artifact
        path: sh
        args:
        - -exc
        - |
          tar xzf api-*.tgz -C ../api-artifact-extract
  - put: cf-production
    params:
      manifest: api-artifact-extract/deployment/manifest-production.yml
      environment_variables:
        TWITTER_CONSUMER-KEY: ((twitter.production.consumer-key))
        TWITTER_CONSUMER-SECRET: ((twitter.production.consumer-secret))
        TWITTER_ACCESS-TOKEN: ((twitter.production.access-token))
        TWITTER_ACCESS-TOKEN-SECRET: ((twitter.production.access-token-secret))
- name: chat web production
  serial: true
  plan:
  - aggregate:
    - get: ci-image
    - get: chat-web-artifact
      trigger: true
      passed:
      - e2e
  - task: extract chat web
    image: ci-image
    config:
      inputs:
      - name: chat-web-artifact
      outputs:
      - name: chat-web-artifact-extract
      platform: linux
      run:
        dir: chat-web-artifact
        path: sh
        args:
        - -exc
        - |
          tar xzf chat-web-*.tgz -C ../chat-web-artifact-extract
  - put: cf-production
    params:
      manifest: chat-web-artifact-extract/deployment/manifest-production.yml
- name: chat backend production
  serial: true
  plan:
  - aggregate:
    - get: ci-image
    - get: chat-backend-artifact
      trigger: true
      passed:
      - e2e
  - task: extract chat backend
    image: ci-image
    config:
      inputs:
      - name: chat-backend-artifact
      outputs:
      - name: chat-backend-artifact-extract
      platform: linux
      run:
        dir: chat-backend-artifact
        path: sh
        args:
        - -exc
        - |
          tar xzf chat-backend-*.tgz -C ../chat-backend-artifact-extract
  - put: cf-production
    params:
      manifest: chat-backend-artifact-extract/deployment/manifest-production.yml

resource_types:
- name: semver-latest
  type: docker-image
  source:
    repository: concourse/semver-resource
- name: google-cloud-storage
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: api-version
  type: semver-latest
  source:
    driver: gcs
    bucket: twauth-versions
    key: api-version
    json_key: ((gcr-key))
- name: chat-web-version
  type: semver-latest
  source:
    driver: gcs
    bucket: twauth-versions
    key: chat-web-version
    json_key: ((gcr-key))
- name: chat-backend-version
  type: semver-latest
  source:
    driver: gcs
    bucket: twauth-versions
    key: chat-backend-version
    json_key: ((gcr-key))
- name: api-artifact
  type: google-cloud-storage
  source:
    bucket: twauth-artifacts
    json_key: ((gcr-key))
    regexp: api-(.*).tgz
- name: chat-web-artifact
  type: google-cloud-storage
  source:
    bucket: twauth-artifacts
    json_key: ((gcr-key))
    regexp: chat-web-(.*).tgz
- name: chat-backend-artifact
  type: google-cloud-storage
  source:
    bucket: twauth-artifacts
    json_key: ((gcr-key))
    regexp: chat-backend-(.*).tgz
- name: api-source
  type: git
  source:
    uri: https://github.com/codebandits/twauth.git
    branch: master
    paths:
    - api
- name: chat-web-source
  type: git
  source:
    uri: https://github.com/codebandits/twauth.git
    branch: master
    paths:
    - chat/web
- name: chat-backend-source
  type: git
  source:
    uri: https://github.com/codebandits/twauth.git
    branch: master
    paths:
    - chat/backend
- name: e2e-source
  type: git
  source:
    uri: https://github.com/codebandits/twauth.git
    branch: master
    paths:
    - e2e
- name: ci-image-source
  type: git
  source:
    uri: https://github.com/codebandits/twauth.git
    branch: master
    paths:
    - ci/docker
- name: ci-image
  type: docker-image
  source:
    repository: gcr.io/twauth-178923/ci
    username: _json_key
    password: ((gcr-key))
- name: cf-ci
  type: cf
  source:
    api: ((cf.api))
    username: ((cf.username))
    password: ((cf.password))
    organization: ((cf.organization))
    space: ci
- name: cf-production
  type: cf
  source:
    api: ((cf.api))
    username: ((cf.username))
    password: ((cf.password))
    organization: ((cf.organization))
    space: production

groups:
- name: pipeline
  jobs:
  - api
  - chat web
  - chat backend
  - e2e
  - api production
  - chat web production
  - chat backend production
- name: ci-image
  jobs:
  - publish ci image
