jobs:

- name: publish ci image
  plan:
  - get: ci-image-source
    trigger: true
  - put: ci-image
    params:
      build: ci-image-source/ci/docker

- name: api
  plan:
  - get: ci-image
    passed: [publish ci image]
    trigger: true
  - get: api-source
    trigger: true
  - task: test and build
    image: ci-image
    config:
      inputs:
      - name: api-source
      outputs:
      - name: api-build
      platform: linux
      run:
        dir: api-source
        path: sh
        args:
        - -exc
        - |
          ./gradlew api:test api:assemble
          mkdir -p ../api-build/build/libs
          cp -r api/build/libs/api-0.0.1-SNAPSHOT.jar ../api-build/build/libs
          cp -r api/deployment ../api-build
  - put: cf-ci
    params:
      manifest: api-build/deployment/manifest-ci.yml

- name: chat
  plan:
  - get: ci-image
    passed: [publish ci image]
    trigger: true
  - get: chat-source
    trigger: true
  - task: test and build
    image: ci-image
    config:
      inputs:
      - name: chat-source
      outputs:
      - name: chat-build
      platform: linux
      run:
        dir: chat-source
        path: sh
        args:
        - -exc
        - |
          ./gradlew chat:yarn_install chat:yarn_test chat:yarn_run_build
          cp -r chat/deployment chat/build ../chat-build
  - put: cf-ci
    params:
      manifest: chat-build/deployment/manifest-ci.yml

- name: e2e
  plan:
  - get: e2e-source
    trigger: true
  - get: cf-ci
    trigger: true
    passed: [api, chat]
  - get: ci-image
    passed: [publish ci image]
  - task: end to end tests
    image: ci-image
    params:
      API_URL: http://twauth-api-ci.cfapps.io/
      CHAT_URL: http://twauth-chat-ci.cfapps.io/
    config:
      inputs:
      - name: e2e-source
      platform: linux
      run:
        dir: e2e-source
        path: xvfb-run
        args:
        - -a
        - ./gradlew
        - e2e:yarn_install
        - e2e:yarn_test

resources:
- name: api-source
  type: git
  source:
    uri: https://github.com/codebandits/twauth.git
    branch: master
    paths:
    - api
- name: chat-source
  type: git
  source:
    uri: https://github.com/codebandits/twauth.git
    branch: master
    paths:
    - chat
- name: e2e-source
  type: git
  source:
    uri: https://github.com/codebandits/twauth.git
    branch: master
    paths:
    - e2e
- name: ci-image-source
  type: git
  source:
    uri: https://github.com/codebandits/twauth.git
    branch: master
    paths:
    - ci/docker
- name: ci-image
  type: docker-image
  source:
    repository: gcr.io/twauth-178923/ci
    username: _json_key
    password: ((gcr-key))
- name: cf-ci
  type: cf
  source:
    api: ((cf.api))
    username: ((cf.username))
    password: ((cf.password))
    organization: ((cf.organization))
    space: ci

groups:
- name: pipeline
  jobs:
  - api
  - chat
  - e2e
- name: ci-image
  jobs:
  - publish ci image
